# -*- coding: utf-8 -*-
"""Shrishti Assignment 1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tAKZ9lMPLRmU9S1ER872RYPCuu0nxw2J
"""



"""Q.Write down 3-5 methods applicable to each data type. ANS- Integer: abs(), round(), pow()

Strings: upper(), lower(), split(), join(), replace()

Lists: append(), pop(), sort(), reverse(), index()

Tuples: count(), index(), len(), max(), min()

Dictionaries: get(), update(), keys(), values()

Sets: add(), remove(), union(), intersection(), difference()
"""



#Q-Define a function, which takes in two strings A and B. Reverses the first string A, adds it to B, and returns the final string.
def reverse(a,b):
    r=a[::-1]
    return b+r 
print(reverse("hello world","IIIT hyderabad"))

#Q-Given a list having Names, work_hours, and gender, Write a function to print name of the female worker that worked the most hours. Also how much do should she be paid if the pay is $ 20 per hour.
#work_hours = [('Abby',100 , 'F'),('Billy',400, 'M'),('Cassie',800,'F'), ('Maggi',600,'F'),('Alex',500,'M'),('Raj',225,'M'),('Penny',920,'F'),('Ben',300,'M')]
#Answer : the female worker that worked the most hours is Penny and she should be paid 18400
def work(l):
  f_wh=[]
  for n,h,g in l:
    if g == 'F':
      f_wh.append((n,h))
  f_wh.sort(key=lambda x: x[1],reverse=True)
  max=f_wh[0]
  name,hours=max
  pay = hours * 20
  print(f"The female worker that worked most hours is {name} and she should be paid {pay}")
work_hours = [('Abby',100 , 'F'),('Billy',400, 'M'),('Cassie',800,'F'), ('Maggi',600,'F'),('Alex',500,'M'),('Raj',225,'M'),('Penny',920,'F'),('Ben',300,'M')]
work(work_hours)

#Q-a)Create a 5x5 matrix of the following form,[[1,1][2,2]]i.e. each row is increasing and has repetive elements. Hint : you can use hstack, vstack etc.
#b) find dot product of the matrix with any matrix. (Figure out the size/ shape of the matrix
import numpy as np
matrixA = np.repeat(np.arange(1, 6), 2).reshape(2, 5)
print(matrixA)
matrixB = np.arange(1,16).reshape(5,3)
print(matrixB)
dot_product = np.dot(matrixA, matrixB)
print(dot_product)

## Question 3 : Upload an image to your google drive, Use plt.imread to read image from the google drive and then print that image using plt.imshow
!pip install matplotlib
from google.colab import drive
drive.mount('/content/drive')
from google.colab import files
uploaded = files.upload()
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
file_name = 'machine_learning_mind_map_3.png'
image = mpimg.imread(file_name)

plt.imshow(image)
plt.axis('on')
plt.show()